#!/bin/sh
# list_clients - print JSON list of clients on UniFi managed network
# Andrew Ho (andrew@zeuscat.com)
#
# Filters and sorts the data from api/s/default/stat/sta to show a subset
# of information useful for a human to identifying devices on the network.
#
# Requires unifi_functions.sh and unifi_credentials.sh in your $PATH
# as well as jq (https://stedolan.github.io/jq/) for working with JSON.

ME=$(basename -- "$0")
warn() { echo "$ME: $@" 1>&2; }
die() { echo "$ME: $@" 1>&2; exit 1; }

source unifi_functions.sh
source unifi_credentials.sh

unifi_login "$UNIFI_BASEURL" "$UNIFI_USERNAME" "$UNIFI_PASSWORD"
[ $? -eq 0 ] || die 'could not log in to UniFi Cloud Key'

# Fetch interesting subset of information from client list, sort by name
unifi_fetch api/s/default/stat/sta |
    jq '[.data[] | {name,hostname,ip,essid,is_wired,oui} | del(.[] | nulls)]' |
    jq 'sort_by(.name,.hostname,.ip)'
